### ISSUE TITLE
Support for Dolly models

### ISSUE THREAD

**Issue by vv9k** [rustformers/llm#142]
There are some pretty fresh models available from DataBricks called [Dolly]() trained using GPT-J. I've found one converted to GGML and quantized but it fails to run with `llama-rs`. It'd be nice to add support for those models as they seem to be promising for commercial usage.

Currently, I'm getting this error using `main` branch:
```
❯ RUST_BACKTRACE=1 cargo r --bin llama-cli --release -- infer -m ~/dev/llm/int4_fixed_zero.bin -p "Tell me about yourself"
    Finished release [optimized] target(s) in 0.05s
     Running `target/release/llama-cli infer -m /dev/llm/int4_fixed_zero.bin -p 'Tell me about yourself'`
[2023-04-16T16:03:16Z INFO  llama_cli::cli_args] ggml ctx size = 6316.05 MB

[2023-04-16T16:03:16Z INFO  llama_cli::cli_args] Loading model part 1/1 from '/dev/llm/int4_fixed_zero.bin'

thread 'main' panicked at 'Could not load model: UnknownTensor { tensor_name: "gpt_neox.embed_in.weight", path: "/dev/llm/int4_fixed_zero.bin" }', llama-cli/src/cli_args.rs:311:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/result.rs:1790:5
   3: llama_cli::cli_args::ModelLoad::load
   4: llama_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Upstream discussion: https://github.com/ggerganov/llama.cpp/discussions/569
Dolly GGML Q4 model: https://huggingface.co/snphs/dolly-v2-12b-q4
https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm

**Comment by philpax** [comment]
Dolly v2 is based on Pythia, which is a slightly different model architecture. I think it shouldn't be too hard to do this, but it'll require someone to implement the architecture. We should be in a much better place to do this once #141 lands.

**Comment by danforbes** [comment]
Care to assign this to me? https://github.com/ggerganov/ggml/blob/master/examples/dolly-v2/main.cpp

**Comment by danforbes** [comment]
Here's the WIP...tried to make this commit as a sort of template for future model-implementers https://github.com/danforbes/llama-rs/commit/a8c31fb28fa473d89acc7718f438a4e7fe70cc58
