### ISSUE TITLE
Support for GPT-J

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#144]
GPT-J is [EleutherAI's older open-source model](https://huggingface.co/EleutherAI/gpt-j-6b). While not as powerful as the newer models, it's still popular as a finetuning base.

@LLukas22 mentioned an interest on working on this: https://github.com/rustformers/ecosystem/issues/1#issuecomment-1514865570

**Comment by danforbes** [comment]
You can assign this to me as well https://github.com/danforbes/llama-rs/tree/dfo/model/gptj

**Comment by philpax** [comment]
Done in #168
