### ISSUE TITLE
Related to stop prompt 

### ISSUE THREAD

**Issue by hlhr202** [rustformers/llm#151]
Hi, some models got very stupid stopping logic (eg. vicuna under instruct mode)
llama-rs can provide a way (like a stop prompt argument) to stop it by giving a text sequence.
What I v investigated are as follows:

https://github.com/Atome-FE/llama-node/blob/main/packages/llama-cpp/src/llama.rs#L152
https://github.com/sobelio/llm-chain/blob/main/llm-chain-llama/src/executor.rs#L96

I think llama.cpp also provide something called reverse prompt or anti prompt (but they just use it in interactive mode)

**Comment by LLukas22** [comment]
I agree that adding stop word/sequence support natively would be helpful for using models in a chatbot setting, especially ones that aren't specifically trained for that purpose. Perhaps we could add a list of strings to the `InferenceParameters`, tokenize them, and then match the last N-generated tokens against the tokenized stop words. This should be easy enough and would prevent models from talking to themselves 😓.

**Comment by danforbes** [comment]
Here is a naive implementation https://github.com/danforbes/llama-rs/commit/4d15b0995c471402fac5150dde4262c241e9902a

**Comment by philpax** [comment]
@danforbes Sorry, keep forgetting to get back to you on this! Yeah that seems fine to me, want to add `antiprompt: Option<&str>` to `inference_with_prompt`?

**Comment by danforbes** [comment]
You need to provide more information than just the "reverse prompt" - among other things you need to provide some kind of callback for receiving user input. There are also some changes to the way that returned tokens are handled (EOT handling as well as reverse prompt handling) that I wasn't sure how to implement cleanly in the existing `inference_with_prompt` function.

**Comment by danforbes** [comment]
@hlhr202 this should be implemented with #206, but please open another Issue if you have more suggestions 🙏🏻
