### ISSUE TITLE
BLOOM does not seem to produce meaningful output

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#163]
Using https://huggingface.co/Wauplin/bloomz-7b1.cpp/blob/main/ggml-model-bloomz-7b1-f16-q4_0.bin:

```rust
# cargo run --release --bin llm bloom infer -m models/bloom/ggml-model-bloomz-7b1-f16-q4_0.bin -p "Translate 'hello world' to Spanish."

[...]

[2023-05-01T02:11:49Z INFO  llm::cli_args] Model fully loaded! Elapsed: 2596ms
<s>Translate 'hello world' to Spanish.
```

(i.e. it does not produce any output after the full stop.)

However, leaving it incomplete leads it to generate output, just not particularly meaningful output:
```rust
# cargo run --release --bin llm bloom infer -m models/bloom/ggml-model-bloomz-7b1-f16-q4_0.bin -p "Translate 'hello world' to Spanish"

[...]

[2023-05-01T02:12:45Z INFO  llm::cli_args] Model fully loaded! Elapsed: 1499ms
<s>Translate 'hello world' to Spanish-language learners whoo queensuite dediaryan, ankeeping a.
```

This is probably an issue with the inference somewhere.

**Comment by hhamud** [comment]
I'll try this one as well

**Comment by hhamud** [comment]
I haven't managed to be able to replicate the 0 output after a full stop but still get garbled nonsense

**Comment by hhamud** [comment]
The same problem does sometimes happen to this [model](https://github.com/NouamaneTazi/bloomz.cpp) as well 

```
user@Users-Laptop bloomz.cpp % ./main -m ~/models/ggml-model-bloomz-1b1-f16-q4_0.bin -t 8 -n 128 -p "Translate 'Hello world' into Spanish."
main: seed = 1683228204
bloom_model_load: loading model from '/Users/user/models/ggml-model-bloomz-1b1-f16-q4_0.bin' - please wait ...
bloom_model_load: n_vocab = 250880
bloom_model_load: n_ctx   = 512
bloom_model_load: n_embd  = 1536
bloom_model_load: n_mult  = 1
bloom_model_load: n_head  = 16
bloom_model_load: n_layer = 24
bloom_model_load: f16     = 2
bloom_model_load: n_ff    = 6144
bloom_model_load: n_parts = 1
bloom_model_load: ggml ctx size = 1010.71 MB
bloom_model_load: memory_size =   144.00 MB, n_mem = 12288
bloom_model_load: loading model part 1/1 from '/Users/user/models/ggml-model-bloomz-1b1-f16-q4_0.bin'
bloom_model_load: .................................... done
bloom_model_load: model size =   866.23 MB / num tensors = 294

main: prompt: 'Translate 'Hello world' into Spanish.'
main: number of tokens in prompt = 8
153772 -> 'Translate'
 69996 -> ' 'H'
 10800 -> 'ello'
  8876 -> ' world'
    10 -> '''
  3727 -> ' into'
 49063 -> ' Spanish'
   503 -> '.'

sampling parameters: temp = 0.800000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.300000


Translate 'Hello world' into Spanish.</s> [end of text]


main: mem per token =  7971508 bytes
main:     load time =   512.12 ms
main:   sample time =    24.62 ms
main:  predict time =    82.65 ms / 10.33 ms per token
main:    total time =   724.79 ms
user@Users-Laptop bloomz.cpp % 

```

**Comment by danforbes** [comment]
The biggest difference I can find in the bloomz.cpp implementation and the one in this repo has to do with the calculation of the `k_q_v` value during evaluation https://github.com/rustformers/llm/blob/de1c447/crates/models/bloom/src/lib.rs#L291-L320

**Comment by dustletter** [comment]
bloomz.cpp must have been forked just before a change to GGML that forbade matrix-multiply on permuted vectors.
I don't think the linked workaround can work, if the goal is to get the same output as the commented-out code - the `ggml_is_transposed()` assertion looks at the tensor strides, rather than a "permuted" flag on the tensor.  But the dimension transforms are pretty far over my head, I could be wrong.

The approach in the commit that added the assertion was to copy the tensor: https://github.com/ggerganov/ggml/commit/acd4aeee95cc47f06ab007962453b40e03af8e88#diff-f0282d7dc99b60a206ebcc1a53809d7188aa21edd61c72e9ec4be1667945ffbcL511
