### ISSUE TITLE
Skip over the BOS token where possible

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#187]
BLOOM will always produce the BOS token (`<s>`) at the start of its output, and we should probably strip this from the output. However, we need to make sure we do this in a way that won't interfere with any other models, and also won't lead to tokens being implicitly dropped.

I'm thinking we add a `bos_token_id(&self) -> Option<TokenId>` (and maybe rename `eot_token_id` to `eos_token_id`) to the `Model` trait, and then have `feed_prompt` just not call the `callback` if the token's the BOS.

**Comment by danforbes** [comment]
I wonder how much of this type of logic can/should be surfaced at the inference callback layer?

**Comment by philpax** [comment]
Yes, I'm not entirely sure myself. The general thinking we've had is that `infer_with_params` does "what you expect" and if you want more control, you can explicitly call `infer_next_token`, but `feed_prompt` is prior to the inference process.

At the same time, I can't think of any reason you'd want to keep the original BOS in a production context. The only time I can see that being useful is when you're testing the model starts and ends messages as it should.

Right now, the BOS is exposed to the user, but the EOS/EOT isn't (as it stops inferring) - this means you get messages like `<s>What's 1+1? 2`, which just looks odd.
