### ISSUE TITLE
Official support for Wizard?

### ISSUE THREAD

**Issue by kameko** [rustformers/llm#189]
https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML

It would be nice to have support for an unencumbered model. Censored models don't seem to be as good at following prompts.

**Comment by hhamud** [comment]
If it's based on Llama you should be able to run it using the LLama command
`llm llama infer -m <path to Wizard model here> -p "prompt"`

**Comment by philpax** [comment]
I've confirmed that one of TheBloke's WizardLM models works with LLaMA.
