### ISSUE TITLE
Support for GGML BLAS

### ISSUE THREAD

**Issue by darxkies** [rustformers/llm#190]
It would be great if BLAS could be enabled in GGML by the user. Enabling BLAS does significantly enhance the performance of GGML. I have tested llama.cpp/GGML with cublas, and it really pays off enabling it.

**Comment by darxkies** [comment]
[cublas-patch.txt](https://github.com/rustformers/llm/files/11415839/cublas-patch.txt)

Ugly patch to add support for cuBLAS.

**Comment by virajk31** [comment]
Thanks, can CBLAS be enabled as well ?

**Comment by darxkies** [comment]
CLBlast can be enabled for Linux and Windows using the PR #282.

**Comment by philpax** [comment]
Is this done now?

**Comment by darxkies** [comment]
From my POV, it is.
