### ISSUE TITLE
Support for LoRA adapters?

### ISSUE THREAD

**Issue by NatanFreeman** [rustformers/llm#196]
I was just wondering if there was support for loading LLaMA models with LoRA weights applied like [llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master/examples/main) has. I couldn't find any existing discussions about this. This project would be perfect for my use case but only if this is possible.

**Comment by philpax** [comment]
Not at the moment, but we'd love to support it at some point.

**Comment by NatanFreeman** [comment]
Is case someone wants to contribute, what would be involved in implementing this?

**Comment by philpax** [comment]
It's somewhat involved - you would have to replicate this function https://github.com/ggerganov/llama.cpp/blob/master/llama.cpp#L2151, which loads both the LoRA and the original model, and then patches the tensors with the LoRA data.

Our abstractions are different (especially in how we handle model loading), so it's not going to be the most straightforward thing. That being said, if you or anyone else is interested, I'd encourage you to swing by [our Discord](https://discord.gg/YB9WaXYAWU) to chat to us about how to do it.

**Comment by LLukas22** [comment]
@NatanFreeman Could you provide a LoRA adapter and a matching base model in ggml format? Or could you point us to somewhere where we can find one?

**Comment by NatanFreeman** [comment]
For the base model I just converted the [LLaMA weights](https://huggingface.co/decapoda-research/llama-7b-hf/tree/main) using [convert-pth-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-pth-to-ggml.py). I cannot provide the LoRA adapter I am using because it was trained on private data. Instead, you can use [these LoRA weights](https://huggingface.co/samwit/alpaca7B-lora/tree/main) and convert them using [convert-lora-to-ggml.py](https://github.com/ggerganov/llama.cpp/blob/master/convert-lora-to-ggml.py) to get weights in the same format.

**Comment by daniel-vainsencher** [comment]
Sorry if there is a well known answer, but why would you fuse the Lora layers into the rest of the model? The fact that a single model can have different variants just by swapping out the (relatively) tiny Lora layers is a feature, no?

**Comment by LLukas22** [comment]
@daniel-vainsencher LoRA is applied by patching the weights of existing layers in a model via `patched_tensor = original_tensor + BA *s`. The B and A Tensors are provided by the lora adapter. The base model is patched in-memory meaning if you want to apply a different LoRA adapter you simply have to reload the model with a different adapter.

**Comment by daniel-vainsencher** [comment]
Got it, thanks for explaining the what, but I asked about the why. 

Instead you can use at inference time 

Patched * x as Original*x + A(Bx) 

which is cheap because A, B are each small. This exactly allows us to avoid swapping out the large O(riginal) weights, and instead be able to infere on multiple Lora variants of the same model by just swapping out their A, B.

**Comment by LLukas22** [comment]
@daniel-vainsencher Oh alright, atm we don't have good abstractions on the inference side for the implemented architectures. If we wanted to apply the LoRA weights during inference we would need to update the inference code for every existing and upcoming architecture. I wanted to keep compatability with the existing codebase and decided to apply the patches during loading. This way we don't have to change any inference code and its simpler to port over existing implementations from e.g. llama.cpp.

Maybe in the future when we have better abstractions layers we could move the LoRA adapter back into the inference function.
But that's also debatable as we want to execute only needed calculations, even if they are relatively simple. By applying the weights during loading we only have to calculate them once and not every inference call 🤔

**Comment by philpax** [comment]
Done in #211

**Comment by LLukas22** [comment]
@NatanFreeman well i can point you towards this https://github.com/rustformers/llm/pull/211#issue-1705736482 . But its basically the normal [inference code](https://github.com/rustformers/llm/blob/main/crates/llm/examples/inference.rs) and you just have to add an optional parameter to the `ModelParameters` while loading the model. If you have any problems let me know.

**Comment by NatanFreeman** [comment]
It works. Is there away of using multiple LoRAs on top of each other?

**Comment by LLukas22** [comment]
Uhm not right now, i dont even know how that would work. Are they patching the same Tensors or different ones? And If they are patching the same tensors the order in which the adapters are applied would be important.

Could you please explain how the patching process works with multiple files?

**Comment by NatanFreeman** [comment]
I'm not sure how the implementation is done but this Python code cell works:
```py
from peft import PeftModel
from transformers import LLaMATokenizer, LLaMAForCausalLM, GenerationConfig

tokenizer = LLaMATokenizer.from_pretrained("decapoda-research/llama-7b-hf")

model = LLaMAForCausalLM.from_pretrained(
    "decapoda-research/llama-7b-hf",
    load_in_8bit=True,
    device_map="auto",
)
model = PeftModel.from_pretrained(model, "Naataan/Model-A")
model = PeftModel.from_pretrained(model, "Naataan/Model-B")

# save the applied weights to a new bin file
PROMPT = """Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Natan: Hello.
Name the 3 biggest cities in England
### Response:"""

inputs = tokenizer(
    PROMPT,
    return_tensors="pt",
)
input_ids = inputs["input_ids"].cuda()

generation_config = GenerationConfig(
    temperature=0.6,
    top_p=0.95,
    repetition_penalty=1.15,
)
print("Generating...")
generation_output = model.generate(
    input_ids=input_ids,
    generation_config=generation_config,
    return_dict_in_generate=True,
    output_scores=True,
    max_new_tokens=128,
)
for s in generation_output.sequences:
    print(tokenizer.decode(s))
```
Perhaps the `peft` documentation has the answer.

**Comment by LLukas22** [comment]
Alright i probably have to read some `peft` source code and check what they are doing. I'm gonna create a new issue for this.

Oh and i would greatly appreciate it if you could provide/link to any LoRA adapter that's split into multiple parts :D
