### ISSUE TITLE
How can I stop the inference to include the prompt tokens?

### ISSUE THREAD

**Issue by juliooa** [rustformers/llm#205]
If I call this:
```
> llm llama infer -m <model_path> -p "Tell me how cool the Rust programming language is: "
```
I get:
```
✓ Loaded 291 tensors (4.2 GB) after 144ms
Tell me how cool the Rust programming language is:
The first thing that comes to mind when I think about rust... 
```
I'm not sure if this is something from `llm`, but it always includes the initial prompt in the inference, can I tell it to not do that?
When I try the same in llama.cpp it doesn't include the initial prompt.
To be clear, I want to achieve this:
```
✓ Loaded 291 tensors (4.2 GB) after 144ms
The first thing that comes to mind when I think about rust... 
```
I can manually take it out, but I'm curious if there is a way to remove it with the crate.

Thanks for the crate!

**Comment by danforbes** [comment]
At this time that is not possible - prompt tokens are sent to the inference callback function just like all other tokens (Ref: https://github.com/rustformers/llm/blob/main/crates/llm-base/src/inference_session.rs#L100) There have been discussions about giving downstream users more information and control about how and why the callback function is being called.

**Comment by philpax** [comment]
Copying this across from Discord: I like that proposal, but I'm not sure about having the error in the `Response` (I can't think of too many applications where you'd want to still run the callback after a failure), and the `Feedback` should have a way to return an error (`Halt` could potentially take a `Option<E: Error>`, maybe?)

Something like
```rust
pub enum InferenceResponse<'a> {
    PromptToken(&'a str),
    InferredToken(&'a str),
    EotToken,
}

pub enum InferenceFeedback<'a, E: Error + 'static> {
    Continue,
    FeedPrompt(&'a str),
    Halt(Option<E>),
}
```
perhaps?

**Comment by juliooa** [comment]
Cool, thanks for the replies, this looks great.

**Comment by danforbes** [comment]
Closing now that the above has been merged in.

**Comment by philpax** [comment]
Not quite yet - there's still no way to hide the prompt being shown in the CLI. Fixing now...

**Comment by danforbes** [comment]
Ah, I see...

**Comment by philpax** [comment]
*Now* we're sorted 😂
