### ISSUE TITLE
Split up initial and per-message prompts for chat mode

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#216]
At present, the chat mode will apply the same prompt template for every single user prompt. This makes sense for REPL mode, where you want to reuse the same prompt (e.g. Alpaca instructions), but it doesn't make sense for chat mode, where you want to continue a conversation:

```
[Initial prompt]

User: [user input]
[Chat response prompt] [bot's response]
User: [user input]
[Chat response prompt] [bot's response]
```

That is to say, `Initial prompt` and `Chat response prompt` should be different.

**Comment by danforbes** [comment]
Just a totally random nitpick, but I think it would be great if the top-level `examples` folder could be removed (or at least renamed) as a part of this effort.

**Comment by ralyodio** [comment]
i agree on both counts.
