### ISSUE TITLE
Support for `GPTBigCode`

### ISSUE THREAD

**Issue by ekolawole** [rustformers/llm#222]
What we need is local cpp for llm "HuggingFaceH4/starchat-alpha A". It  is much better than any other open source chat models at coding. And it does very well at chatting too. This is better than Vicuna.

**Comment by philpax** [comment]
https://huggingface.co/docs/transformers/model_doc/gpt_bigcode

https://huggingface.co/HuggingFaceH4/starchat-alpha/blob/main/config.json

Looks to be a GPT-2 variant.

**Comment by LLukas22** [comment]
This should be solved with the last GPT-2 changes.
