### ISSUE TITLE
error failed to run custom build command for `ggml-sys v0.1.1  on Macos

### ISSUE THREAD

**Issue by realcarlos** [rustformers/llm#223]
I want to call llm from a Flutter project , what should I change?

Caused by:
  process didn't exit successfully: `/Users/xxx/llm/target/release/build/ggml-sys-a701dcd7fa05cfc8/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=ggml
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-apple-darwin")
  HOST = Some("x86_64-apple-darwin")
  cargo:rerun-if-env-changed=CC_x86_64-apple-darwin
  CC_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_x86_64_apple_darwin
  CC_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-apple-darwin
  CFLAGS_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_apple_darwin
  CFLAGS_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  cargo:rustc-link-lib=framework=Accelerate
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "./ggml/include/ggml" "-pthread" "-mavx" "-mavx2" "-mfma" "-mf16c" "-msse3" "-DGGML_USE_ACCELERATE" "-DNDEBUG" "-o" "/Users/xxx/llm/target/release/build/ggml-sys-78f6d4347bdd5b7a/out/ggml/src/ggml.o" "-c" "ggml/src/ggml.c"
  cargo:warning=clang: error: no such file or directory: 'ggml/src/ggml.c'
  cargo:warning=clang: error: no input files
  exit status: 1

  --- stderr

  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "./ggml/include/ggml" "-pthread" "-mavx" "-mavx2" "-mfma" "-mf16c" "-msse3" "-DGGML_USE_ACCELERATE" "-DNDEBUG" "-o" "/Users/xxx/llm/target/release/build/ggml-sys-78f6d4347bdd5b7a/out/ggml/src/ggml.o" "-c" "ggml/src/ggml.c" with args "cc" did not execute successfully (status code exit status: 1).

**Comment by philpax** [comment]
You need to retrieve the submodules - try `git submodule update --init`.

**Comment by realcarlos** [comment]
> You need to retrieve the submodules - try `git submodule update --init`.

thank you solved.
