### ISSUE TITLE
Support multiple LoRA adapters 

### ISSUE THREAD

**Issue by LLukas22** [rustformers/llm#227]
Accoring to @NatanFreeman `peft` supports the use of multiple LoRA adapters for the same model. 
The following is valid python code:
```python
from peft import PeftModel
from transformers import LLaMATokenizer, LLaMAForCausalLM, GenerationConfig

tokenizer = LLaMATokenizer.from_pretrained("decapoda-research/llama-7b-hf")

model = LLaMAForCausalLM.from_pretrained(
    "decapoda-research/llama-7b-hf",
    load_in_8bit=True,
    device_map="auto",
)
model = PeftModel.from_pretrained(model, "Naataan/Model-A")
model = PeftModel.from_pretrained(model, "Naataan/Model-B")

# save the applied weights to a new bin file
PROMPT = """Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Natan: Hello.
Name the 3 biggest cities in England
### Response:"""

inputs = tokenizer(
    PROMPT,
    return_tensors="pt",
)
input_ids = inputs["input_ids"].cuda()

generation_config = GenerationConfig(
    temperature=0.6,
    top_p=0.95,
    repetition_penalty=1.15,
)
print("Generating...")
generation_output = model.generate(
    input_ids=input_ids,
    generation_config=generation_config,
    return_dict_in_generate=True,
    output_scores=True,
    max_new_tokens=128,
)
for s in generation_output.sequences:
    print(tokenizer.decode(s))
```

We probably have to check how `peft` handles the patching of multiple tensors and implement it.

**Comment by philpax** [comment]
I wonder if just running the patches in sequence works? e.g. patching with the `LoraAdapter` for `Model-A`, followed by the `LoraAdapter` for `Model-B`

**Comment by LLukas22** [comment]
Alright after some `peft` source code reading and head scratching this is what i found out. There are 2 ways to apply multiple LoRA Adapters.

The first method is the method described above e.g.
```
model = PeftModel.from_pretrained(model, "Model1")
model = PeftModel.from_pretrained(model, "Model1")
```
This will wrap the wrapped model again resulting in something like this: `Model2(Model1(BaseModel(input)))`.
To support this we simply have to apply the adapters in the right order e.g. : (base + LoRA_1) + LoRA_2
With LoRA_1  and 2 being the LoRA  formula of `w= w+BA*s` with their respectiv A,B and scaling tensors. 
Its important to note that weights can be patched twice by this but this is not always the case.

The second  method simply swaps the Adapter on the fly, i don't think we need to support this, as the user can simply reload the model with the new adapter.

**Comment by daniel-vainsencher** [comment]
Apologize in advance if the following is not helpful...

In the world of math, since applying a single LoRa [1] layer is $(W+A_1B_1)x$, applying two has only one meaning $(W+A_1B_1+A_2B_2)x$, and similarly for more. Since matrix addition is commutative, associative etc, it doesn't matter what order you apply them in. 

Now, working with floating point numbers, none of that is strictly true, and especially with highly quantized (e.g., 8bit, 4bit) floats. However, if you can compute everything with full floats and then re-quantize, you have a good approximation.

In terms of memory $A,B$ are usually much smaller than $AB$, so for minimal memory reqs, you want to compute the full adjustment for a chunk of AB at a time, then modify W in place.

[1] https://arxiv.org/pdf/2106.09685.pdf Eq 3 and the preceding paragraph

**Comment by daniel-vainsencher** [comment]
BTW, I think that method 2 is super useful in some usecases where the latency of reloading W from disk is prohibitive, e.g., swapping between my code-completion finetuned bot and my email-authoring bot, or even more so swapping between multiple agents collaborating among themselves.

**Comment by LLukas22** [comment]
@daniel-vainsencher Thanks for the hints, atm. we are forced to apply the patches inplace as we dont want to break compatability with the existing implementations. 

I agree with you on the usefullness of method 2, but  currently we don't have the prerequisites to apply the patches during inference.  If you want to you can create an issue for this but we first have to implement an abstraction layer to make this possible. 

For the time being im probably going to implement a CLI command which will combine a basemodel with LoRA patches and export it. This way the patched model can be loaded via `mmap` to speedup the loading times dramatically, with the tradeoff of using more diskspace.

**Comment by daniel-vainsencher** [comment]
@LLukas22: got it no problem, you'd explained the pre-req problem to me before. I opened #231 for the fast-swappable LoRa, which BTW also proposes a way to keep reloading fast even when weights are being merged by subtracting the old LoRa and adding in the new.
