### ISSUE TITLE
How to run these models?

### ISSUE THREAD

**Issue by realcarlos** [rustformers/llm#230]
These are what I tried:

cargo run --release --bin llm gpt2 infer -m cerebras-2.7b-q4_0.bin -p "Tell me how cool the Rust programming language is:"

cargo run --release --bin llm gptj infer -m GPT-J-6B-Pygway-ggml-q4_0.bin -p "Tell me how cool the Rust programming language is:"

got the errors:
⣾ Loading model...Error: 
   0: Could not load model
   1: multipart models are not supported

cargo run --release --bin llm bloom infer -m models/ggml-model-bloomz-560m-f16-q4_0.bin -p "Tell me how cool the Rust programming language is:"

could work ,but output is strange :

Tell me how cool the Rust programming language is:,.
,: )B Ireidr
        Cone;urOgM  doI LteE em from parT SiaFun1P Bate //
	.L be herand ( M ;），。2 D！
		 
h
               .
 Theod？Glo(x,.
,: )B Ireidr
        Cone;urOgM  doI willkE em from Lte SiaTie1unP parR
	. Bate // be (Lintand，）。 M ; D！
		F.

                Theod2 com was est,.

**Comment by ralyodio** [comment]
it says multimodel is not supported, doesn't sound like a missing path to me.

**Comment by LLukas22** [comment]
I just experienced something similar, when the CLI couldn't find the specified file and started to search in the directory for *.bin files, which resulted in the "multimodel is not supported" error.

**Comment by danforbes** [comment]
I have also experienced problems with output from quantized BLOOM models https://github.com/rustformers/llm/issues/228 Maybe try with a different model? As the other commenters have said, the warning about multi-part models is usually a red herring related to human error when entering the path to the model.

**Comment by ralyodio** [comment]
The example code for me just runs in a loop continuously now. weird.

**Comment by philpax** [comment]
The multipart models error should only come up if there are files with the same filename and a numeric suffix. I'd be interested in seeing what was in the directory and where the models came from.

**Comment by danforbes** [comment]
> The example code for me just runs in a loop continuously now. weird.

The example inference.rs code should run (generate text) until the model produces an end-of-text token, at which point some stats will be printed to the terminal and the example will exit. Is that not the behavior you're experiencing?

> The multipart models error should only come up if there are files with the same filename and a numeric suffix. I'd be interested in seeing what was in the directory and where the models came from.

Have you tried this yourself? I'm pretty sure this is the behavior when you point `llm` to an invalid model path, at least in my experience.

**Comment by philpax** [comment]
> Have you tried this yourself? I'm pretty sure this is the behavior when you point `llm` to an invalid model path, at least in my experience.

Oops, I think this was fixed and unfixed at some point. Refixed!

**Comment by philpax** [comment]
@realcarlos Can you download some recent (last 2-3 days) models and try again? There have been a few changes with the format that invalidate existing models (I'm working on a shim for them), but in the meantime it'd be good to know if you're still experiencing this.

**Comment by danforbes** [comment]
@realcarlos - I'm going to close this Issue, but please feel free to reopen it or open a new one if you have more questions.

**Comment by realcarlos** [comment]
> @realcarlos Can you download some recent (last 2-3 days) models and try again? There have been a few changes with the format that invalidate existing models (I'm working on a shim for them), but in the meantime it'd be good to know if you're still experiencing this.

Thanks @philpax , finally ,I could run it with  llm llama infer -m ggml-model-q4_0.bin -p "Tell me how cool the Rust programming language is:"

and it will be great if we could have a list of available models.

**Comment by realcarlos** [comment]
> @realcarlos - I'm going to close this Issue, but please feel free to reopen it or open a new one if you have more questions.

sure ,thank you @danforbes

**Comment by DanWizard** [comment]
Running into this issue where can I find a list of supported models?

**Comment by LLukas22** [comment]
[rustformers](https://huggingface.co/rustformers) or nearly all GGMLV3 models from [TheBloke](https://huggingface.co/TheBloke).

**Comment by philpax** [comment]
Check out https://github.com/rustformers/llm/blob/main/doc/known-good-models.md as well.
