### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by mhykes** [rustformers/llm#234]
Hi.  I tried both of the procedures under Building llm-cli in your readme.  Both of them give me an error where the curtom build command for ggml-sys c0.1.1 fails.

I'm in an Ubuntu 18.04 devcontainer and don't need any kind of cross compilation.  I don't see any sign that cross compilation is the problem.

stderr is:
```
error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "ggml/include/ggml" "-I" "legacy" "-pthread" "-mavx" "-mavx2" "-mfma" "-mf16c" "-msse3" "-DNDEBUG" "-o" "/workspaces/rust-tools/llm/target/release/build/ggml-sys-2a7930b36525a1be/out/ggml/src/ggml.o" "-c" "ggml/src/ggml.c" with args "cc" did not execute successfully (status code exit status: 1).
```

Warnings provide a little more information:
```
warning: ggml/src/ggml.c: In function 'bytes_from_nibbles_32':
warning: ggml/src/ggml.c:534:27: warning: implicit declaration of function '_mm256_set_m128i'; did you mean '_mm256_set_epi8'? [-Wimplicit-function-declaration]
warning:      const __m256i bytes = _mm256_set_m128i(_mm_srli_epi16(tmp, 4), tmp);
warning:                            ^~~~~~~~~~~~~~~~
warning:                            _mm256_set_epi8
warning: ggml/src/ggml.c:534:27: error: incompatible types when initializing type '__m256i {aka const __vector(4) long long int}' using type 'int'
```

I really want to try llm specifically with BLOOM.  This seems like a great project if I can get it to build.

**Comment by philpax** [comment]
Hm, that's quite odd. That would imply that it's being built with AVX support enabled, but your C compiler doesn't have those intrinsics available.

There's a chance that your 18.04 container doesn't have definitions/implementations of those intrinsics, assuming this is correct and the relevant patch was submitted in 2017: https://patchwork.ozlabs.org/project/gcc/patch/4E89A029A0F8D443B436A5167BA3C53F19949559@IRSMSX101.ger.corp.intel.com/

Can you try with a newer container?

**Comment by mhykes** [comment]
Hey thanks.  Updating to Ubuntu 22.04 resolved my problem.  I was able to build from source and test the bloom model listed on the [known-good models](https://github.com/rustformers/llm/blob/main/known-good-models.md) page.  

The non-quantized model from that repo gives not-so-helpful results, while the quantized model causes a panic.  But that's a different issue, so still progress. Thank you.

**Comment by philpax** [comment]
Yeah, we have an issue with BLOOM quantization right now: #228. Hoping to get to the bottom of it soon!
