### ISSUE TITLE
cargo build --release error cargo:warning=cc1: fatal error: ggml/src/ggml.c: No such file or directory

### ISSUE THREAD

**Issue by Micost** [rustformers/llm#264]
Found an issue when try to cargo build --release

error message 

  Compiling ggml-sys v0.1.1 (/home/rob/llm/crates/ggml/sys)
The following warnings were emitted during compilation:

warning: cc1: fatal error: ggml/src/ggml.c: No such file or directory
warning: compilation terminated.

error: failed to run custom build command for `ggml-sys v0.1.1 (/home/rob/llm/crates/ggml/sys)`

Caused by:
  process didn't exit successfully: `/home/rob/llm/target/release/build/ggml-sys-e7677f9beb0f9605/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=ggml
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "ggml/include/ggml" "-I" "legacy" "-pthread" "-mavx" "-mf16c" "-msse3" "-DNDEBUG" "-o" "/home/rob/llm/target/release/build/ggml-sys-2a7930b36525a1be/out/ggml/src/ggml.o" "-c" "ggml/src/ggml.c"
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "ggml/include/ggml" "-I" "legacy" "-pthread" "-mavx" "-mf16c" "-msse3" "-DNDEBUG" "-o" "/home/rob/llm/target/release/build/ggml-sys-2a7930b36525a1be/out/legacy/qnt0.o" "-c" "legacy/qnt0.c"
  cargo:warning=cc1: fatal error: ggml/src/ggml.c: No such file or directory
  cargo:warning=compilation terminated.
  exit status: 1
  exit status: 0

  --- stderr

  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "ggml/include/ggml" "-I" "legacy" "-pthread" "-mavx" "-mf16c" "-msse3" "-DNDEBUG" "-o" "/home/rob/llm/target/release/build/ggml-sys-2a7930b36525a1be/out/ggml/src/ggml.o" "-c" "ggml/src/ggml.c" with args "cc" did not execute successfully (status code exit status: 1).

**Comment by botatooo** [comment]
I think you've yet to pull in submodules, so try running `git submodule init && git submodule update`

**Comment by Micost** [comment]
T

> 

Thanks for your help , it works now,
