### ISSUE TITLE
Update to latest upstream GPT-J implementation

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#265]

**Comment by danforbes** [comment]
Can you specify what has changed?

**Comment by philpax** [comment]
Good question. At a glance, it doesn't seem like much:
https://github.com/ggerganov/ggml/compare/4fdfcb923c6dbb3346bc524bb12b4e666024fc6c..765c9bce37a53c36da4723e9f014874c27b69aa1#diff-3f5388a1be1f359a34550ff575896f85fe8c315a4b57c113aabcfceb8f2b1be3

If we confirm that the inplace calls all match, we should be able to close this one I think

**Comment by philpax** [comment]
No changes
