### ISSUE TITLE
llm-llama's old version of rust-tokenizers and protobuf conflicts with rust-bert

### ISSUE THREAD

**Issue by dimfeld** [rustformers/llm#269]
llm-llama has a dependency of protobuf pinned to exactly version 2.14 and rust-tokenizers 3.1.2 (which also requires =2.14).

When I include both `rust-bert` and `llm` in the same project, this causes issues because rust-bert uses rust-tokenizers 8.1, which requires some changes in more recent versions of protobuf.

For now I'm just disabling the llama feature completely in my code which gets things building again, but at some point I'll probably want to turn that back on.

It appears that upgrading the convert code in llm-llama to use rust-tokenizers 8 would be somewhat complex, if even possible.  So it seems like the easiest solution, at least for now, would be to expose the `llm-llama/convert` feature from the `llm` crate so that it can be disabled. 

Any thoughts?

**Comment by philpax** [comment]
Ah, good catch! We're not currently using the `convert` code anyway, so the easiest solution might be to remove that entirely and revisit it once we can better handle it.

**Comment by dimfeld** [comment]
Thanks for the quick fix!

**Comment by philpax** [comment]
Glad to hear it :)
