### ISSUE TITLE
MPT-7B error during inference: Assertion `ggml_nelements(src1) == 3' failed

### ISSUE THREAD

**Issue by troyedwardsjr** [rustformers/llm#281]
Getting this error when trying to run inference on any of these models: https://huggingface.co/rustformers/mpt-7b-ggml

Windows:
```
Loaded hyperparameters
ggml ctx size = 3567.88 MB

Loaded tensor 8/194
Loaded tensor 16/194
Loaded tensor 24/194
Loaded tensor 32/194
Loaded tensor 40/194
Loaded tensor 48/194
Loaded tensor 56/194
Loaded tensor 64/194
Loaded tensor 72/194
Loaded tensor 80/194
Loaded tensor 88/194
Loaded tensor 96/194
Loaded tensor 104/194
Loaded tensor 112/194
Loaded tensor 120/194
Loaded tensor 128/194
Loaded tensor 136/194
Loaded tensor 144/194
Loaded tensor 152/194
Loaded tensor 160/194
Loaded tensor 168/194
Loaded tensor 176/194
Loaded tensor 184/194
Loaded tensor 192/194
Loading of model complete
Model size = 3568.33 MB / num tensors = 194
Assertion failed: ggml_nelements(src1) == 3, file ggml/src/ggml.c, line 10838
error: process didn't exit successfully: exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

WSL (Ubuntu VM):
```
Loaded hyperparameters
ggml ctx size = 3567.88 MB

Loaded tensor 8/194
Loaded tensor 16/194
Loaded tensor 24/194
Loaded tensor 32/194
Loaded tensor 40/194
Loaded tensor 48/194
Loaded tensor 56/194
Loaded tensor 64/194
Loaded tensor 72/194
Loaded tensor 80/194
Loaded tensor 88/194
Loaded tensor 96/194
Loaded tensor 104/194
Loaded tensor 112/194
Loaded tensor 120/194
Loaded tensor 128/194
Loaded tensor 136/194
Loaded tensor 144/194
Loaded tensor 152/194
Loaded tensor 160/194
Loaded tensor 168/194
Loaded tensor 176/194
Loaded tensor 184/194
Loaded tensor 192/194
Loading of model complete
Model size = 3568.33 MB / num tensors = 194
ggml/src/ggml.c:10838: ggml_compute_forward_alibi_f32: Assertion `ggml_nelements(src1) == 3' failed.
Aborted
```

Code to reproduce:
```rust
use llm::{Model, InferenceParameters};
use std::io::Write;

fn main() {
    let model = llm::load::<llm::models::Mpt>(
        std::path::Path::new("./models/mpt-7b-instruct-q4_0.bin"),
        Default::default(),
        None,
        llm::load_progress_callback_stdout
    )
    .unwrap_or_else(|err| panic!("Failed to load model: {err}"));

    let mut session = model.start_session(Default::default());

    let res = session.infer::<std::convert::Infallible>(
        &model,
        &mut rand::thread_rng(),
        &llm::InferenceRequest {
            prompt: "### Human: Rust is a cool programming language because
            ### Assistant: ".into(),
            parameters: &llm::InferenceParameters::default(),
            play_back_previous_tokens: false,
            maximum_token_count: None,
        },
        // OutputRequest
        &mut Default::default(),
        |r| match r {
            llm::InferenceResponse::PromptToken(t) | llm::InferenceResponse::InferredToken(t) => {
                print!("{t}");
                std::io::stdout().flush().unwrap();

                Ok(llm::InferenceFeedback::Continue)
            }
            _ => Ok(llm::InferenceFeedback::Continue),
        },
    );

    match res {
        Ok(result) => println!("\n\nInference stats:\n{result}"),
        Err(err) => println!("\n{err}"),
    }
}
```

**Comment by LLukas22** [comment]
I tested it on my part and on the main branch everything works as expected. Could you please make sure ggml is up to date by running a `git submodule update --recursive --remote` in your project? If that doesn't work please provide the hash of the model you are using and your git revision.

**Comment by troyedwardsjr** [comment]
@LLukas22 
Specs with 3080 Ti:
![image](https://github.com/rustformers/llm/assets/16667416/b569af9e-a910-49a4-9eab-e36ee4ea5df8)

I used this `llm = { git = "https://github.com/rustformers/llm", branch="main" }` with `cargo clean + cargo run` but I'll try cloning it and using local path and `git submodule update --init --recursive` right now if that's what you wanted which pulled this ggml submodule `[.gitmodules](https://github.com/rustformers/llm/blob/main/.gitmodules)`.

```
$ git submodule update --init --recursive
Submodule 'crates/ggml/sys/ggml' (https://github.com/ggerganov/ggml.git) registered for path 'crates/ggml/sys/ggml'
Cloning into 'C:/dev/mindtwin/old/mindtwin_prototype_llm/llm/crates/ggml/sys/ggml'...
Submodule path 'crates/ggml/sys/ggml': checked out '72dbb51c0900dcb10c4efbf18deb7b4b440d6ad4'
```

`llm = { path="./llm/crates/llm" }`
```
md5sum mpt-7b-q4_0.bin       
c26dce5eb1bf1f5bfccaa56be96c613e  mpt-7b-q4_0.bin
md5sum mpt-7b-instruct-q4_0.bin
741aba88bad62361cae057029d30e34e  mpt-7b-instruct-q4_0.bin
sha256sum  mpt-7b-instruct-q4_0.bin
701ecd6c0919543af5e4a42f08d6adf227b586fd2d16e0ea76263e318efe640b  mpt-7b-instruct-q4_0.bin
sha256sum  mpt-7b-q4_0.bin
08c72599cd9aba00989addf35806ae000ebd6e6290eb6f9d3e9ea3f81e5ab1de  mpt-7b-q4_0.bin
```

llm repo git revision:
```
$ git rev-parse HEAD
3ad021bac5074a8906c2e467d85c11293ac132ea
```

Same error:
```
Loaded hyperparameters
ggml ctx size = 3567.88 MB

Loaded tensor 8/194
Loaded tensor 16/194
Loaded tensor 24/194
Loaded tensor 32/194
Loaded tensor 40/194
Loaded tensor 48/194
Loaded tensor 56/194
Loaded tensor 64/194
Loaded tensor 72/194
Loaded tensor 80/194
Loaded tensor 88/194
Loaded tensor 96/194
Loaded tensor 104/194
Loaded tensor 112/194
Loaded tensor 120/194
Loaded tensor 128/194
Loaded tensor 136/194
Loaded tensor 144/194
Loaded tensor 152/194
Loaded tensor 160/194
Loaded tensor 168/194
Loaded tensor 176/194
Loaded tensor 184/194
Loaded tensor 192/194
Loading of model complete
Model size = 3568.33 MB / num tensors = 194
Assertion failed: ggml_nelements(src1) == 3, file ggml/src/ggml.c, line 10833
error: process didn't exit successfully: `target\debug\mindtwin_prototype.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by tye-singwa** [comment]
hi! having same problem, seems that it is ggml issue, 
this https://github.com/ggerganov/ggml/blob/07bd0114365c7cb0cbb2ad8297d7a64788f882c4/src/ggml.c#LL10897C1-L10897C12
and this https://github.com/ggerganov/ggml/blob/07bd0114365c7cb0cbb2ad8297d7a64788f882c4/src/ggml.c#L10833 
does not work with this code https://github.com/ggerganov/ggml/blob/07bd0114365c7cb0cbb2ad8297d7a64788f882c4/src/ggml.c#LL6320C8-L6320C8

**Comment by philpax** [comment]
This is very weird! I just tested out MPT on macOS M1 with the latest version of `llm` and with both our models and The-Bloke's, and it seems to work for me:

```
     Running `target/release/llm mpt infer -m models/mpt/mpt-7b-instruct.ggmlv3.q5_1.bin -p 'Hey what'\''s up?'`
✓ Loaded 194 tensors (5.0 GB) after 2711ms
Hey what's up?
This is a discussion on Heyo within the Community forums, part of the General category; Hi I'm back^C

     Running `target/release/llm mpt infer -m models/mpt/mpt-7b-instruct-q4_0-ggjt.bin -p 'Hey what'\''s up?'`
✓ Loaded 194 tensors (3.7 GB) after 89ms
Hey what's up?
You're not logged in. Please login or register to use this function (it is free).
```

What platforms are you all on? I can test with Windows x86-64 later, but... still baffled that this could happen.

**Comment by philpax** [comment]
Hm, @LLukas22 suspects it might be an issue with the CLI vs the library (which shouldn't happen, but see my previous bafflement). Does the CLI work for you?

**Comment by tye-singwa** [comment]
i think that this is reproducible only for `dev` profile, cause `assert` being removed otherwise

**Comment by philpax** [comment]
Thanks for picking that up! You're right, we usually build in release. We'll have to see if we can improve that for future :)

Looking forward to seeing how the GGML patch goes.

**Comment by philpax** [comment]
Confirmed that the latest version of GGML fixes the debug assert for me. Thanks for figuring this out, @tye-singwa!

**Comment by troyedwardsjr** [comment]
@tye-singwa @LLukas22 @philpax Hmm, is this the expected output?

mpt-7b-instruct-q4_0.bin:
```
Loaded hyperparameters
ggml ctx size = 3567.88 MB

Loaded tensor 8/194
Loaded tensor 16/194
Loaded tensor 24/194
Loaded tensor 32/194
Loaded tensor 80/194
Loaded tensor 88/194
Loaded tensor 96/194
Loaded tensor 104/194
Loaded tensor 112/194
Loaded tensor 120/194
Loaded tensor 128/194
Loaded tensor 136/194
Loaded tensor 144/194
Loaded tensor 152/194
Loaded tensor 160/194
Loaded tensor 168/194
Loaded tensor 176/194
Loaded tensor 184/194
Loaded tensor 192/194
Loading of model complete
Model size = 3568.33 MB / num tensors = 194
### Human: Rust is a cool programming language because
            ### Assistant: ##################################


Inference stats:
feed_prompt_duration: 14523ms
prompt_tokens: 16
predict_duration: 20930ms
predict_tokens: 22
per_token_duration: 951.364ms
```

mpt-7b-q4_0.bin: (Really interesting output on this one)
```
Loaded hyperparameters
ggml ctx size = 3567.88 MB

Loaded tensor 8/194
Loaded tensor 16/194
Loaded tensor 24/194
Loaded tensor 32/194
Loaded tensor 40/194
Loaded tensor 48/194
Loaded tensor 56/194
Loaded tensor 64/194
Loaded tensor 72/194
Loaded tensor 80/194
Loaded tensor 88/194
Loaded tensor 96/194
Loaded tensor 104/194
Loaded tensor 112/194
Loaded tensor 120/194
Loaded tensor 128/194
Loaded tensor 136/194
Loaded tensor 144/194
Loaded tensor 152/194
Loaded tensor 160/194
Loaded tensor 168/194
Loaded tensor 176/194
Loaded tensor 184/194
Loaded tensor 192/194
Loading of model complete
Model size = 3568.33 MB / num tensors = 194
### Human: Rust is a cool programming language because
            ### Assistant: ###

### Assistant: Thank you, user! ������ ###

```

    ██��  ███��   ██�� ��█████�� ��█��     ██████�� ����██�� ��█████����      ███��   ██��██��███��  ██�� ��█████�� ��█████�� 
       ����─�� ��─── │ ��������═��� [1] <--- START --- // TASK 1 ---------------------------------------->                  [2] /usr/bin/[3]./file.py                                       <-- END --->  
              ────────────��          //         ��                     ��             \033['5D'     
   ─��                   `\\'\033[[0;32m')�� (Ctrl+C) to exit           //                    ��     
         ___\/\\_,\\/\\\___ _ __ `___,____ ___ \\]{7~} \\\[_]\\{(6~\\[{\\) \[[\)\\]\(4~^ \~\>��¯º��´¶«¬³¨¥»ç²¼ð½¸¿¹¾ñ£®©™ßª°±…¡¢��­×����·•¦§ ‘†‡�� ″—∼µ��Ï€“����–��–��■ÃÄÖÑüäàòêëíïôúûüýĀ����������������������ьи��є��дэзжзийкклъмннопрсшщыюзфийкаччяяцщекжеежзабаваябаевыйзабавлезволеньомособенохороскоподеликожалостойтеплоуместницагерогамиллионушегургутинимстаньтесяпримутваткотечкуеточисткиторостокуснитесвидятсяйысьжжјёёїюъű������ո����ո��ա������������
```

```rust
use llm::{Model, InferenceParameters};
use std::io::Write;

fn main() {
    let model = llm::load::<llm::models::Mpt>(
        std::path::Path::new("./models/mpt-7b-q4_0.bin"),
        Default::default(),
        None,
        llm::load_progress_callback_stdout
    )
    .unwrap_or_else(|err| panic!("Failed to load model: {err}"));

    let mut session = model.start_session(Default::default());

    let res = session.infer::<std::convert::Infallible>(
        &model,
        &mut rand::thread_rng(),
        &llm::InferenceRequest {
            prompt: "### Human: Rust is a cool programming language because
            ### Assistant: ".into(),
            parameters: &llm::InferenceParameters::default(),
            play_back_previous_tokens: false,
            maximum_token_count: None,
        },
        // OutputRequest
        &mut Default::default(),
        |r| match r {
            llm::InferenceResponse::PromptToken(t) | llm::InferenceResponse::InferredToken(t) => {
                print!("{t}");
                std::io::stdout().flush().unwrap();

                Ok(llm::InferenceFeedback::Continue)
            }
            _ => Ok(llm::InferenceFeedback::Continue),
        },
    );

    match res {
        Ok(result) => println!("\n\nInference stats:\n{result}"),
        Err(err) => println!("\n{err}"),
    }
}
```

**Comment by troyedwardsjr** [comment]
Maybe it's just my VS Code terminal because of the ANSI escape sequences? Just tried in Windows terminal / Powershell with mpt-7b-q4_0.bin and the output seems to make more sense. This context is weirdly relevant to me despite giving no context to the LLM so far since I helped with Flecs (which is written in C?), very odd/coincidental output haha.

```
Model size = 3568.33 MB / num tensors = 194
### Human: Rust is a cool programming language because
            ### Assistant: ######

- [Rusty](https://github.com/SanderMertens) has been creating some very interesting projects in the past few weeks, and it's about time I share them with you guys! The first project that he worked on was called 'Cargo Container', which allows users to play around C++11 code without having any prior knowledge of this new standard (but they can still have fun anyway). It contains three parts;
```

**Comment by philpax** [comment]
It looks like your prompt has extra spaces on the second line, which is confusing the model. The instruct model recovers from it a little, but the non-instruct model just gets confused and tries to continue it.

If I try your original prompt:
```
     Running `target/release/llm mpt infer -m models/mpt/mpt-7b-instruct-q4_0-ggjt.bin -f test.txt --no-mmap`
✓ Loaded 194 tensors (3.7 GB) after 780ms
### Human: Rust is a cool programming language because

            ### Assistant: I've never used it but I have friends who do. They really like how easy it makes parallel processing and networking code.
Assistant: OK, you'll need to use your laptop or computer's Bluetooth capability for this project. So if the keyboard has an on/off switch or button, make sure that is in "on" mode before connecting via bluetooth because sometimes when a device powers off its internal power saving battery also turns it off so don't get confused^C
```
If I try the CLI with
```
### Human: Rust is a cool programming language because

### Assistant:

```

I get
```
### Human: Rust is a cool programming language because

### Assistant: Cool, tell me more about why you think that.
```

(I also don't know if that's the correcting prompting style for MPT - we should maybe document the more standard ones somewhere)

**Comment by LLukas22** [comment]
@troyedwardsjr From my experiments MPT Instruct seams to suffer a lot from the q4_0 quantization, i also played around with the q5_1 version which performed a lot better. If you want i could upload it or you can convert it form the pytorch version via [llm-rs-python](https://github.com/LLukas22/llm-rs-python).

**Comment by vilhelmbergsoe** [comment]
@LLukas22 Have you tried / had any luck using GPTQ quantization with the MPT 7B model? If so did you notice any better performance at lower bit quantization?
I'd also be interested in understanding how I might quantize MPT using GPTQ myself, so if anyone has any resources let me know :)

**Comment by troyedwardsjr** [comment]
> @troyedwardsjr From my experiments MPT Instruct seams to suffer a lot from the q4_0 quantization, i also played around with the q5_1 version which performed a lot better. If you want i could upload it or you can convert it form the pytorch version via [llm-rs-python](https://github.com/LLukas22/llm-rs-python).

Sure thing! If you could upload the q5_1 version it'd be much appreciated, and I'll report back to you with the results.

**Comment by LLukas22** [comment]
@vilhelmbergsoe No i haven't played around with GPTQ as im mostly focused on CPU inference. But [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) looks like a good starting point if you want to look into it. I would expect similar performance to GGMLs quantization technices.

@troyedwardsjr Ok i upload it, should be done in about 30 minutes, but i wont update the readme today. You can find the model in the `files` section.

**Comment by troyedwardsjr** [comment]
> @vilhelmbergsoe No i haven't played around with GPTQ as im mostly focused on CPU inference. But [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) looks like a good starting point if you want to look into it. I would expect similar performance to GGMLs quantization technices.
> 
> @troyedwardsjr Ok i upload it, should be done in about 30 minutes, but i wont update the readme today. You can find the model in the `files` section.

The output is still pretty bad. I'm curious why MPT suffers so much from quantization butVicuna and other 7b parameter models I've tried do not.
