### ISSUE TITLE
invalid file format version 2

### ISSUE THREAD

**Issue by GiusTex** [rustformers/llm#294]
I'm trying to load [pygmalion-7b-ggml](https://huggingface.co/waifu-workshop/pygmalion-7b-ggml-q5_1/tree/main) with:
`llm llama infer --model-path C:\Users\myusername\.cache\huggingface\hub\models--mayaeary--opt-1.3b\ggml-pygmalion-7b-q5_1.bin --prompt "Rust is a cool programming language because"`, but I get:
```
⣾ Loading model...Error:
   0: Could not load model
   1: invalid file format version 2

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: BaseThreadInitThunk<unknown>
      at <unknown source file>:<unknown line>
   2: RtlUserThreadStart<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```
The model folder name isn't right but it should't stop the code from finding the model; if I change model and folder I still get an error (a different one).

I installed rustformers llm with cargo, and I'm on Windows 11. I tried also `-r user/model` but I got `-r not recognised`.

**Comment by danforbes** [comment]
It's possible that this model is too old 😭 The ecosystem has been moving very quickly.

**Comment by GiusTex** [comment]
Interesting, I'll try more models then

**Comment by LLukas22** [comment]
Currently you have to use the newest version directly from "Main" If you want to use the newest models. The 0.1.1 release only supports older models and fails on new models. The HF tokenizer option `r` is also only available in the main branch.

**Comment by GiusTex** [comment]
Thanks ! I'll try installing rustformers-llm from source (if this is what you mean with "main") and use something from the Bloke then when I get up

**Comment by LLukas22** [comment]
@GiusTex `git clone --recurse-submodules git@github.com:rustformers/llm.git` expects you to have your ssh keys setup correctly. You can also clone via `https` without setting them up. Try something similar to this:
```
git clone --recurse-submodules https://github.com/rustformers/llm.git
cd llm
cargo build --release
```
we should probably change this in the README 🤔

**Comment by GiusTex** [comment]
Awesome, now I have the build from source, thanks again! Now I can test the TheBloke's models

**Comment by LLukas22** [comment]
Pygamelion is a gptj based model. Which means instead of running it with `llama infer` you have to run it with `gptj infer`. You also can't quantize it via LLama.cpp as it isn't llama based. You could use rustformers quantization function.

**Comment by GiusTex** [comment]
Thanks, I thought using llama was fine because I used it before in [text-generation-webui](https://github.com/oobabooga/text-generation-webui) using llama and it always worked; thanks also for telling me about the rustformers quantization function (`cargo run --release $MODEL_ARCHITECTURE quantize $MODEL_IN $MODEL_OUT {q4_0,q4_1}`), I forgot it existed

**Comment by LLukas22** [comment]
Converting a Hugging Face model to a quantized GGML model involves more than just running it through the `quantize` function. The process essentially follows these steps: 

1. Obtain Pytorch model
2. Convert to GGML using conversion script
3. Quantize
4. Execute 

To streamline this process, I've gathered the conversion scripts for numerous model architectures and simplified the procedure within the [llm-rs-python](https://github.com/LLukas22/llm-rs-python) project. I encourage you to examine the readme, which includes an example of converting and quantizing a Hugging Face model. 

If you wish to utilize the quantized models outside of Rustformers, please remember to specify `ContainerType.GGML` as the container when using the `AutoQuantizer`.
