### ISSUE TITLE
Ability to await the result of infer

### ISSUE THREAD

**Issue by Lordxan** [rustformers/llm#307]
I was wondering is it possible to use this library without callbacks?

**Comment by danforbes** [comment]
No, this is not possible at this time. I believe the goal of this library is to leave "higher-level" abstractions such as that up to the user. For now, you'd probably want to use probably want to use use a combination of [`InferenceSession::feed_prompt`](https://docs.rs/llm/0.1.1/llm/struct.InferenceSession.html#method.feed_prompt) and [`InferenceSession::infer_next_token`](https://docs.rs/llm/0.1.1/llm/struct.InferenceSession.html#method.infer_next_token) to implement this. I'm going to close this Issue, but please feel free to re-open it or open another one if you have more questions.
