### ISSUE TITLE
Implement jsonformer

### ISSUE THREAD

**Issue by itsbalamurali** [rustformers/llm#314]
Implement jsonformer: https://github.com/1rgs/jsonformer

**Comment by philpax** [comment]
Hi, thanks for requesting this! This is a duplicate of #235 (which is a more general issue), so I'm going to close this, but feel free to vote on that issue to prioritise it :)

**Comment by pixelspark** [comment]
I have an implementation of this using llm, basically it is a `dyn Sampler` you plug in. Can publish as a separate crate (and imho should not be part of `llm` core, although I like the idea in #235 of providing more hooks for guided generation).
