### ISSUE TITLE
CUDA decoding

### ISSUE THREAD

**Issue by jafioti** [rustformers/llm#315]
Hey all, great work on integrating cuda support for the prompt tokens. How much work would it be to support GPU decoding? Currently on llama.cpp I can reach about 35 tokens per second on llama 7B on a 2080 super, and I'd love to reach somewhere near that in rust!

Please lmk if there's anything I can do to help this effort.

**Comment by LLukas22** [comment]
I'm currently working on it and it's already implemented for LLama. If you want to try it here is the branch: https://github.com/LLukas22/llm/tree/cublas-clblast-support 

Example command: `cargo run --release --features cublas -- llama infer -m "C:\Users\lkreu\Downloads\wizardlm-30b.ggmlv3.q4_1.bin" --accelerator-layers 40 --batch-size 512  -p "Write me a short story about a llama riding a crab:"`

Currently i'm trying to implement the acceleration for the other architectures, but some GGML operations are not implemented in CUDA which means i need to perform some of them on the CPU. Currently i'm trying to implement this in a way that doesn't need changes in the existing model implementations.

**Comment by jafioti** [comment]
This is awesome, thanks for the link. I tried it out on my GPU, and it's a lot faster than pure CPU inference. It does seem to be quite a bit slower than llama.cpp (maybe a quarter of the speed, will run measurements). Is it because it's doing CPU sync after every token to run the callback function?

**Comment by LLukas22** [comment]
Well it's still in a pre-draft stage, i'm guessing the creation of a new eval-context each call kills the performance, but that's something to optimize when we get the acceleration working for all models. There was also a lot of work done on the metal branch, which probably will also help us close the gap a bit.

**Comment by malv-c** [comment]
can i expect to test it in my orin agx 32g as an EFI app ?

**Comment by LLukas22** [comment]
@malv-c i don't know what you mean with EFI app. But if you can setup cuda you should be able to compile it for an ARM based system. But maybe we have to adjust the `build.rs` script to enable building with cuda acceleration on ARM 🤔

**Comment by malv-c** [comment]
EFI app to run seriously llm without wasting resources on the poor ubuntu
https://github.com/rust-osdev/uefi-rs

**Comment by jafioti** [comment]
@malv-c Still not sure how this relates to running language models. Why would uefi calls help speed up LLMs?

**Comment by malv-c** [comment]
llm without loading  os  is better than llm+os

**Comment by jafioti** [comment]
That's impractical. 

- Latency / compute constraints don't come from the OS, but from the model size / CUDA kernels / CPU speed. 
- CUDA is usually tightly integrated with the OS as well, so you wouldn't be able to use the GPU. 
- LLMs aren't the only things running, there needs to be some way to interact with the LLM, usually a web server queuing up prompts or some terminal interface. How would that work without an OS?

**Comment by LLukas22** [comment]
@malv-c I agree with @jafioti, the scope of this project will be to provide a good, fast and easy to use llm library. If you want to you can thinker around a bit and see if you get it running  as an EFI app. But i think the ggml backend we are using will be a very problematic to get running correctly.

**Comment by malv-c** [comment]
hi Joe
i strongly disagree but as i don't know rust i will not output code for now
if i find a usable llm ...

**Comment by malv-c** [comment]
hi Lukas not simple i agree
thanks

Le dim. 25 juin 2023 à 21:06, Lukas Kreussel ***@***.***> a
écrit :

**Comment by LLukas22** [comment]
Implemented with https://github.com/rustformers/llm/pull/325
