### ISSUE TITLE
Attempt to guess the architecture of the model if not specified

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#316]
The long-term solution to this will be the implementation of [the GGUF format](https://github.com/ggerganov/ggml/issues/220), but as a concession to practicality now, it may be possible to implement heuristics to guess the architecture of a model.

Heuristics could include:
- fast mmap string-scan for known tensor names, using a ripgrep-like algorithm
- trying to load the model with each architecture and bailing if any invariants are broken
- a cache of hash/filename -> architecture from last use
- some kind of ML solution that classifies based on the first 512 bytes (lol)

We shouldn't spend too much engineering effort on this as actually having the information available is a better solution in the long run, but I imagine GGUF implementation and widespread adoption is at least a month or two away.

**Comment by LLukas22** [comment]
Think we should focus in getting the GGUF format throught. Guessing the architecture is a very hacky solution as we need to try all hyperparameter combinations, and even if we find a matching one we still have to load the model to ensure it's actually the right one

**Comment by philpax** [comment]
Lukas is right, better to focus our efforts on getting a more-informative model format upstream
