### ISSUE TITLE
Tokenization error when inference Bloom with some CJK character

### ISSUE THREAD

**Issue by yangyaofei** [rustformers/llm#323]
Here is the example: 

``` shell
# origin example
cargo run --release --bin llm bloom infer \
    --model-path ./models/ggml-model-phoenix-inst-chat-7b-f16-q4_0.bin \
    --num-ctx-tokens 1024 --num-threads 8 --num-predict 1024 --batch-size 8 \
    -p "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. \
Human: <s>龙卧在溪边，一副倦怠沮丧的样子。汤直胆大，于是去问道：“为什么这么不开心呢？”
龙说：“实不相瞒，我听闻附近城内的佳酿十分淳美，一路赶来，却得知酒已经被商户全买走了。”
汤直便去车上抱了一坛酒送给龙，龙大喜过望，化作一女子抱坛牛饮。
女子说：“你将美酒送我，我该给你什么作为答谢呢？”汤直回答：“一坛酒不过十五六钱，答谢就不必了。”
于是女子掬起一捧溪水给汤直喝，汤直觉得溪水十分清冽，与往常所喝的水截然不同。
女子喝光美酒后对汤直行礼道别，从此以后，汤直就能看见妖鬼了。
###
上面的故事中为什么汤直能看见鬼?</s>
Assistant: <s>"

# the error character
cargo run --release --bin llm bloom infer --model-path ./models/ggml-model-bloomz7b1-f16-q4_0.bin   -p "掬"

```

The given error is :

```
[2023-06-21T07:18:38Z ERROR llm] A tokenization-related failure occurred: an invalid token was encountered during tokenization
```

**Comment by LLukas22** [comment]
Could you try to use the remote Huggingface-Tokenizer via `-r [ORIGINAL_REPO]`? E.g. if [this](https://huggingface.co/FreedomIntelligence/phoenix-inst-chat-7b) was your base model try adding `-r "FreedomIntelligence/phoenix-inst-chat-7b"`.

The integrated tokenizer is lossy and doesn't support all tokenization patterns.

**Comment by yangyaofei** [comment]
@LLukas22 oh, that's good, this project upgrade soooo fast that I can't follow😂.

here is the cmd I use origin bloomz instead:

```
cargo run --release --bin llm bloom infer --model-path ./models/ggml-model-phoenix-inst-chat-7b-f16-q4_0.bin  -r "bigscience/bloomz-7b1-mt"    -p "掬"
```

Is this should a bug or I should close this?

**Comment by LLukas22** [comment]
Theoretically its a bug, but i don't think we will fix the old tokenizer as with the new `GGUF` format the huggingface tokenizer will be included in the model file. The `-r` (remote) parameter can be used until the new format is implemented. I don't think it makes any sense to fix the current tokenizer as we basically completely replace it in the next few weeks with the HF tokenizer.

**Comment by yangyaofei** [comment]
@LLukas22 ok, thank you for your time, close this
