### ISSUE TITLE
Model Load Error:  invariant broken: 1720913039 <= 2

### ISSUE THREAD

**Issue by AnubhabB** [rustformers/llm#349]
I'm trying to load a fine-tuned LLaMA 7B model. The model weights have gone through the following 2 transformations:

1. Used `llama.cpp` > `convert.py` to convert the original weights to `ggml fp16` format - **works**
2. Further used `llama.cpp` > `./quantize` to quantise to `q8_0` format - **works** - tested inference with `llama.cpp`

Now, I'm trying to load the `q8_0` model with:
```
llm::load_dynamic(
            Some(llm::ModelArchitecture::Llama),
            Path::new("/some/model-q8_0.bin"),
            llm::TokenizerSource::Embedded,
            Default::default(),
            llm::load_progress_callback_stdout,
        )?
```
This errors out:
```
invariant broken: 1720913039 <= 2 in Some("/some/model-q8_0.bin")
```

Am I missing something?

**Comment by LLukas22** [comment]
Are you using the 1.1 release or the current main branch?

**Comment by AnubhabB** [comment]
I'm using the current main branch.

**Comment by AnubhabB** [comment]
Never mind. The file was corrupt. Works just fine after a fresh generation.
