### ISSUE TITLE
Wrong instructions for building the CLI

### ISSUE THREAD

**Issue by twardoch** [rustformers/llm#352]
> Building from Source
> To make use of the features on the main branch, clone the repository and then build it with
> 
> ```
> git clone --recurse-submodules git@github.com:rustformers/llm.git
> cargo build --release
> ```

I think this command tries to log into Github with the login `git` or something. It throws errors. It would be better to say: 

```
git clone --recurse-submodules https://github.com/rustformers/llm
cd llm
cargo build --release
```

**Comment by LLukas22** [comment]
Yeah this command tries to authenticate with git via your ssh-keys. Feel free to create a PR with this change.

**Comment by twardoch** [comment]
Meanwhile I’ve added this: https://github.com/rustformers/llm/issues/388
