### ISSUE TITLE
Error compiling CLI: Compiling macro_rules_attribute v0.1.3

### ISSUE THREAD

**Issue by twardoch** [rustformers/llm#353]
On macOS Intel, I tried (also without `--features=metal`: 

```
$ cargo build --release --features=metal
   Compiling macro_rules_attribute v0.1.3
error: Unrecognized option: 'diagnostic-width'

error: could not compile `macro_rules_attribute` (lib)
```

**Comment by philpax** [comment]
That's... rather odd. That's not an issue directly related to us; that would be a transitive dependency.

What version of Rust are you using, and what version of macOS?

**Comment by twardoch** [comment]
Newest macOS Ventura, and I upgraded rust with rustup before trying all this

**Comment by philpax** [comment]
Hm, I honestly have no idea. Can you run the following commands and tell me what the output is?

```
llm # rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
llm # rustup default                       
stable-aarch64-apple-darwin (default)
```

**Comment by twardoch** [comment]
```
$ rustc --version
rustc 1.71.0 (8ede3aae2 2023-07-12)
$ $ rustup default
stable-x86_64-apple-darwin (default)
```

I just did 

```
git pull && cargo update && cargo build --release
```

and got the same failure, but then did:

```
git pull && rustup update && cargo update && cargo build --release
```

and the problem went away. So `rustup update` did fix it.

**Comment by philpax** [comment]
How odd! Well, I'm glad it works now 😅
