### ISSUE TITLE
`ggml-metal.metal` download location?

### ISSUE THREAD

**Issue by twardoch** [rustformers/llm#354]
https://github.com/rustformers/llm/blob/main/doc/CONTRIBUTING.md#acceleration-support-for-building says

```
Metal for GGML requires the ggml-metal.metal file to be located in the same directory as the binary (i.e., target/release/). In future versions, this will likely be embedded in the binary itself.
```

Any chance to provide a link to where `ggml-metal.metal` can be found?

**Comment by philpax** [comment]
Oops! We actually patch GGML metal to transclude the `metal` file, so that's no longer necessary. I'll remove that line - it should just work when you build with Metal support.
