### ISSUE TITLE
Info on getting models?

### ISSUE THREAD

**Issue by twardoch** [rustformers/llm#355]
README says: 

> GGML files are easy to acquire. For a list of models that have been tested, see the [known-good models](https://github.com/rustformers/llm/blob/main/doc/known-good-models.md).

Then `https://github.com/rustformers/llm/blob/main/doc/known-good-models.md` says

> The following models have been tested and are known to work with llm.

But there is no word on **how** to "acquire" them, though this is said to be easy. Which files should be downloaded, where should they be placed (for the CLI to work with them).

**Comment by philpax** [comment]
Ah, right - those link to the repositories, but there are multiple files there. I'll see if I can tweak the wording to make it clearer that you only need one of the files.
