### ISSUE TITLE
Implement SuperHOT/interpolated RoPE support

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#378]
Another llama.cpp feature that seems to have shrunk the paper-to-implementation pipeline to less than one week!

This allows for a much longer context (assuming you have the (V)RAM for it)

- https://github.com/ggerganov/llama.cpp/discussions/1965
- https://github.com/ggerganov/llama.cpp/pull/2019
- https://github.com/ggerganov/llama.cpp/pull/2054

We can probably close out #77 if this is done.

**Comment by LLukas22** [comment]
To do this we only need a new `rope_scaling` model parameter. Or am i missing something?
