### ISSUE TITLE
Installation of CLI on macOS

### ISSUE THREAD

**Issue by twardoch** [rustformers/llm#388]
Feel free to add this somewhere: 

## Installation on macOS

1. Install Rust from the [official website](https://www.rust-lang.org/tools/install)

```bash  
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

2. Navigate to a folder of your choice and clone the `llm` repo: 

```bash
git clone --recurse-submodules https://github.com/rustformers/llm
cd llm
```

3. If you already have rust installed and the `llm` repo cloned, then update everything: 

```bash
git pull && git submodule update --remote --merge && rustup update && cargo update
```

4. Finally, build and install the binaries:

```bash
cargo build --release --features=metal && cargo install --bins --path=./binaries/llm-cli/
```

That should install the `llm` CLI tool into `~/.cargo/bin/llm`. 

5. Use it in Terminal with just `llm` or `~/.cargo/bin/llm`

**Comment by philpax** [comment]
Thank you for writing this up, but I suspect `cargo install --git https://github.com/rustformers/llm.git --features metal llm-cli` should behave identically without requiring the intermediate steps 😅 

Can you check if that works for you?

**Comment by philpax** [comment]
I've updated the README to indicate that you should use `cargo install --git` - hope that resolves this!
