### ISSUE TITLE
Better multiline support in interactive mode

### ISSUE THREAD

**Issue by 0xAlcibiades** [rustformers/llm#53]
~~For longer form interaction, it'd be really nice to add 1) lookback/context 2) better formatting/line returns.~~

@philpax edit: Lookback exists in chat mode. The main thing that this issue now covers is multiline support in interactive mode: you should be able to supply multi-line prompts and have their output rendered correctly.

**Comment by philpax** [comment]
There's overlap with #76 here. We'll need to create a new mode for this and clearly delineate what they do.

**Comment by philpax** [comment]
Lookback/context exists in the new experimental chat model. I'll update this issue to refer to multi-line prompts in interactive mode.

**Comment by philpax** [comment]
Done in #157 🚀
