### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#57]
We should publish the crate and its associated applications to `crates.io` (potentially bringing llamacord etc into a GitHub organization, too). Here's what I think's blocking:

- [x] Move `ggml-rs` to its own publishable crate, add safety warnings
- [x] Fix warnings
- [x] Add deny public docs, document everything
- [x] Get all pending PRs in

Anything else I'm missing, @setzer22 ?

**Comment by philpax** [comment]
Once #81 is done, setzer can publish

**Comment by vv9k** [comment]
This issue has been closed but I don't see a working version on crates.io . Currently there is a version 0.0.0 that contains an empty `main.rs` file printing "hello world". Is the release still to be done or am I looking in the wrong place?

https://docs.rs/crate/llama-rs/latest/source/src/main.rs

**Comment by end-me-please** [comment]
love to see how fast development of this stuff is going
how seamlessly this thing works together with llama-node (compared to the less "clean feeling" llama.cpp) makes me want to start rewriting random stuff in rust (🚀)

especially loving the low number of dependencies compared to the p*thon AI stuff that is used everywhere else

**Comment by philpax** [comment]
We have a RC1 published for all crates 🚀 

My plan is to publish 0.1.1 (I made the mistake of publishing `llm 0.1.0` for reservation) tomorrow.

**Comment by philpax** [comment]
Took a bit longer than expected (had to sneak in an API change), but 0.1.1 is live on crates.io 🎉
