### ISSUE TITLE
Compute perplexity

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#90]
https://github.com/ggerganov/llama.cpp/commit/486ae645fd3eda8b9d7413d5ff34fb65a3e337fb

This should be part of the library (potentially part of `InferenceStats`).

**Comment by tanmaysachan** [comment]
@philpax I implemented it, but could you expand on perplexity being a part of `InferenceStats` ? - since perplexity computation is generally done on prompts and is not a part of inference cycle afaik. Having it as a separate tool (as llama.cpp does) might be the way to go.

**Comment by philpax** [comment]
Hi, awesome to see you've implemented it!

Yes, you're absolutely right - my understanding of the perplexity calculation was wrong when I wrote that issue. It should indeed be separate; I'm not sure what the best interface would be, but I think I'd be fine with `InferenceSession::perplexity` or similar for now.
